/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.ucsd.sccn.lsl;

public class vectorl {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected vectorl(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(vectorl obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        lslAndroidJNI.delete_vectorl(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public vectorl() {
    this(lslAndroidJNI.new_vectorl__SWIG_0(), true);
  }

  public vectorl(long n) {
    this(lslAndroidJNI.new_vectorl__SWIG_1(n), true);
  }

  public long size() {
    return lslAndroidJNI.vectorl_size(swigCPtr, this);
  }

  public long capacity() {
    return lslAndroidJNI.vectorl_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    lslAndroidJNI.vectorl_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return lslAndroidJNI.vectorl_isEmpty(swigCPtr, this);
  }

  public void clear() {
    lslAndroidJNI.vectorl_clear(swigCPtr, this);
  }

  public void add(int x) {
    lslAndroidJNI.vectorl_add(swigCPtr, this, x);
  }

  public int get(int i) {
    return lslAndroidJNI.vectorl_get(swigCPtr, this, i);
  }

  public void set(int i, int val) {
    lslAndroidJNI.vectorl_set(swigCPtr, this, i, val);
  }

}
