/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.ucsd.sccn.lsl;

public class vectorinfo {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected vectorinfo(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(vectorinfo obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        lslAndroidJNI.delete_vectorinfo(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public vectorinfo() {
    this(lslAndroidJNI.new_vectorinfo__SWIG_0(), true);
  }

  public vectorinfo(long n) {
    this(lslAndroidJNI.new_vectorinfo__SWIG_1(n), true);
  }

  public long size() {
    return lslAndroidJNI.vectorinfo_size(swigCPtr, this);
  }

  public long capacity() {
    return lslAndroidJNI.vectorinfo_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    lslAndroidJNI.vectorinfo_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return lslAndroidJNI.vectorinfo_isEmpty(swigCPtr, this);
  }

  public void clear() {
    lslAndroidJNI.vectorinfo_clear(swigCPtr, this);
  }

  public void add(stream_info x) {
    lslAndroidJNI.vectorinfo_add(swigCPtr, this, stream_info.getCPtr(x), x);
  }

  public stream_info get(int i) {
    return new stream_info(lslAndroidJNI.vectorinfo_get(swigCPtr, this, i), false);
  }

  public void set(int i, stream_info val) {
    lslAndroidJNI.vectorinfo_set(swigCPtr, this, i, stream_info.getCPtr(val), val);
  }

}
