# This file was automatically generated by SWIG (http://www.swig.org).
# Version 2.0.9
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.



from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_RecorderLib', [dirname(__file__)])
        except ImportError:
            import _RecorderLib
            return _RecorderLib
        if fp is not None:
            try:
                _mod = imp.load_module('_RecorderLib', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _RecorderLib = swig_import_helper()
    del swig_import_helper
else:
    import _RecorderLib
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0



def cdata(*args):
  return _RecorderLib.cdata(*args)
cdata = _RecorderLib.cdata

def memmove(*args):
  return _RecorderLib.memmove(*args)
memmove = _RecorderLib.memmove

def rl_start_recording(*args):
  return _RecorderLib.rl_start_recording(*args)
rl_start_recording = _RecorderLib.rl_start_recording

def rl_end_recording(*args):
  return _RecorderLib.rl_end_recording(*args)
rl_end_recording = _RecorderLib.rl_end_recording

def new_info(*args):
  return _RecorderLib.new_info(*args)
new_info = _RecorderLib.new_info

def delete_info(*args):
  return _RecorderLib.delete_info(*args)
delete_info = _RecorderLib.delete_info

def info_getitem(*args):
  return _RecorderLib.info_getitem(*args)
info_getitem = _RecorderLib.info_getitem

def info_setitem(*args):
  return _RecorderLib.info_setitem(*args)
info_setitem = _RecorderLib.info_setitem

def new_str(*args):
  return _RecorderLib.new_str(*args)
new_str = _RecorderLib.new_str

def delete_str(*args):
  return _RecorderLib.delete_str(*args)
delete_str = _RecorderLib.delete_str

def str_getitem(*args):
  return _RecorderLib.str_getitem(*args)
str_getitem = _RecorderLib.str_getitem

def str_setitem(*args):
  return _RecorderLib.str_setitem(*args)
str_setitem = _RecorderLib.str_setitem
# This file is compatible with both classic and new-style classes.


