language: cpp
compiler: clang # 3.5 instead of GCC 4.8
env:
  CMakeArgs="-DLSLAPPS_LabRecorder=1 -DLSLAPPS_Examples=1"
script:
- mkdir -p build/install
- cd build
- cmake --version
- cmake -DCMAKE_BUILD_TYPE=Release -DLSL_LSLBOOST_PATH=lslboost -DLSL_UNIXFOLDERS=1 $CMakeArgs ../
- cmake --build . --config Release --target install
- cpack
- cd ..
matrix:
  include:
    - os: osx
      before_install:
        - brew install qt
