/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.example.hellojni;

public class stream_outlet {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected stream_outlet(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(stream_outlet obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        lslAndroidJNI.delete_stream_outlet(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public stream_outlet(stream_info info, int chunk_size, int max_buffered) {
    this(lslAndroidJNI.new_stream_outlet__SWIG_0(stream_info.getCPtr(info), info, chunk_size, max_buffered), true);
  }

  public stream_outlet(stream_info info, int chunk_size) {
    this(lslAndroidJNI.new_stream_outlet__SWIG_1(stream_info.getCPtr(info), info, chunk_size), true);
  }

  public stream_outlet(stream_info info) {
    this(lslAndroidJNI.new_stream_outlet__SWIG_2(stream_info.getCPtr(info), info), true);
  }

  public void push_sample(vectorf data, double timestamp, boolean pushthrough) {
    lslAndroidJNI.stream_outlet_push_sample__SWIG_3(swigCPtr, this, vectorf.getCPtr(data), data, timestamp, pushthrough);
  }

  public void push_sample(vectorf data, double timestamp) {
    lslAndroidJNI.stream_outlet_push_sample__SWIG_4(swigCPtr, this, vectorf.getCPtr(data), data, timestamp);
  }

  public void push_sample(vectorf data) {
    lslAndroidJNI.stream_outlet_push_sample__SWIG_5(swigCPtr, this, vectorf.getCPtr(data), data);
  }

  public void push_sample(vectord data, double timestamp, boolean pushthrough) {
    lslAndroidJNI.stream_outlet_push_sample__SWIG_6(swigCPtr, this, vectord.getCPtr(data), data, timestamp, pushthrough);
  }

  public void push_sample(vectord data, double timestamp) {
    lslAndroidJNI.stream_outlet_push_sample__SWIG_7(swigCPtr, this, vectord.getCPtr(data), data, timestamp);
  }

  public void push_sample(vectord data) {
    lslAndroidJNI.stream_outlet_push_sample__SWIG_8(swigCPtr, this, vectord.getCPtr(data), data);
  }

  public void push_sample(vectorl data, double timestamp, boolean pushthrough) {
    lslAndroidJNI.stream_outlet_push_sample__SWIG_9(swigCPtr, this, vectorl.getCPtr(data), data, timestamp, pushthrough);
  }

  public void push_sample(vectorl data, double timestamp) {
    lslAndroidJNI.stream_outlet_push_sample__SWIG_10(swigCPtr, this, vectorl.getCPtr(data), data, timestamp);
  }

  public void push_sample(vectorl data) {
    lslAndroidJNI.stream_outlet_push_sample__SWIG_11(swigCPtr, this, vectorl.getCPtr(data), data);
  }

  public void push_sample(vectori data, double timestamp, boolean pushthrough) {
    lslAndroidJNI.stream_outlet_push_sample__SWIG_12(swigCPtr, this, vectori.getCPtr(data), data, timestamp, pushthrough);
  }

  public void push_sample(vectori data, double timestamp) {
    lslAndroidJNI.stream_outlet_push_sample__SWIG_13(swigCPtr, this, vectori.getCPtr(data), data, timestamp);
  }

  public void push_sample(vectori data) {
    lslAndroidJNI.stream_outlet_push_sample__SWIG_14(swigCPtr, this, vectori.getCPtr(data), data);
  }

  public void push_sample(vectors data, double timestamp, boolean pushthrough) {
    lslAndroidJNI.stream_outlet_push_sample__SWIG_15(swigCPtr, this, vectors.getCPtr(data), data, timestamp, pushthrough);
  }

  public void push_sample(vectors data, double timestamp) {
    lslAndroidJNI.stream_outlet_push_sample__SWIG_16(swigCPtr, this, vectors.getCPtr(data), data, timestamp);
  }

  public void push_sample(vectors data) {
    lslAndroidJNI.stream_outlet_push_sample__SWIG_17(swigCPtr, this, vectors.getCPtr(data), data);
  }

  public void push_sample(SWIGTYPE_p_std__vectorT_char_t data, double timestamp, boolean pushthrough) {
    lslAndroidJNI.stream_outlet_push_sample__SWIG_18(swigCPtr, this, SWIGTYPE_p_std__vectorT_char_t.getCPtr(data), timestamp, pushthrough);
  }

  public void push_sample(SWIGTYPE_p_std__vectorT_char_t data, double timestamp) {
    lslAndroidJNI.stream_outlet_push_sample__SWIG_19(swigCPtr, this, SWIGTYPE_p_std__vectorT_char_t.getCPtr(data), timestamp);
  }

  public void push_sample(SWIGTYPE_p_std__vectorT_char_t data) {
    lslAndroidJNI.stream_outlet_push_sample__SWIG_20(swigCPtr, this, SWIGTYPE_p_std__vectorT_char_t.getCPtr(data));
  }

  public void push_sample(vectorstr data, double timestamp, boolean pushthrough) {
    lslAndroidJNI.stream_outlet_push_sample__SWIG_21(swigCPtr, this, vectorstr.getCPtr(data), data, timestamp, pushthrough);
  }

  public void push_sample(vectorstr data, double timestamp) {
    lslAndroidJNI.stream_outlet_push_sample__SWIG_22(swigCPtr, this, vectorstr.getCPtr(data), data, timestamp);
  }

  public void push_sample(vectorstr data) {
    lslAndroidJNI.stream_outlet_push_sample__SWIG_23(swigCPtr, this, vectorstr.getCPtr(data), data);
  }

  public void push_sample(SWIGTYPE_p_float data, double timestamp, boolean pushthrough) {
    lslAndroidJNI.stream_outlet_push_sample__SWIG_24(swigCPtr, this, SWIGTYPE_p_float.getCPtr(data), timestamp, pushthrough);
  }

  public void push_sample(SWIGTYPE_p_float data, double timestamp) {
    lslAndroidJNI.stream_outlet_push_sample__SWIG_25(swigCPtr, this, SWIGTYPE_p_float.getCPtr(data), timestamp);
  }

  public void push_sample(SWIGTYPE_p_float data) {
    lslAndroidJNI.stream_outlet_push_sample__SWIG_26(swigCPtr, this, SWIGTYPE_p_float.getCPtr(data));
  }

  public void push_sample(SWIGTYPE_p_double data, double timestamp, boolean pushthrough) {
    lslAndroidJNI.stream_outlet_push_sample__SWIG_27(swigCPtr, this, SWIGTYPE_p_double.getCPtr(data), timestamp, pushthrough);
  }

  public void push_sample(SWIGTYPE_p_double data, double timestamp) {
    lslAndroidJNI.stream_outlet_push_sample__SWIG_28(swigCPtr, this, SWIGTYPE_p_double.getCPtr(data), timestamp);
  }

  public void push_sample(SWIGTYPE_p_double data) {
    lslAndroidJNI.stream_outlet_push_sample__SWIG_29(swigCPtr, this, SWIGTYPE_p_double.getCPtr(data));
  }

  public void push_sample(SWIGTYPE_p_long data, double timestamp, boolean pushthrough) {
    lslAndroidJNI.stream_outlet_push_sample__SWIG_30(swigCPtr, this, SWIGTYPE_p_long.getCPtr(data), timestamp, pushthrough);
  }

  public void push_sample(SWIGTYPE_p_long data, double timestamp) {
    lslAndroidJNI.stream_outlet_push_sample__SWIG_31(swigCPtr, this, SWIGTYPE_p_long.getCPtr(data), timestamp);
  }

  public void push_sample(SWIGTYPE_p_long data) {
    lslAndroidJNI.stream_outlet_push_sample__SWIG_32(swigCPtr, this, SWIGTYPE_p_long.getCPtr(data));
  }

  public void push_sample(SWIGTYPE_p_int data, double timestamp, boolean pushthrough) {
    lslAndroidJNI.stream_outlet_push_sample__SWIG_33(swigCPtr, this, SWIGTYPE_p_int.getCPtr(data), timestamp, pushthrough);
  }

  public void push_sample(SWIGTYPE_p_int data, double timestamp) {
    lslAndroidJNI.stream_outlet_push_sample__SWIG_34(swigCPtr, this, SWIGTYPE_p_int.getCPtr(data), timestamp);
  }

  public void push_sample(SWIGTYPE_p_int data) {
    lslAndroidJNI.stream_outlet_push_sample__SWIG_35(swigCPtr, this, SWIGTYPE_p_int.getCPtr(data));
  }

  public void push_sample(SWIGTYPE_p_short data, double timestamp, boolean pushthrough) {
    lslAndroidJNI.stream_outlet_push_sample__SWIG_36(swigCPtr, this, SWIGTYPE_p_short.getCPtr(data), timestamp, pushthrough);
  }

  public void push_sample(SWIGTYPE_p_short data, double timestamp) {
    lslAndroidJNI.stream_outlet_push_sample__SWIG_37(swigCPtr, this, SWIGTYPE_p_short.getCPtr(data), timestamp);
  }

  public void push_sample(SWIGTYPE_p_short data) {
    lslAndroidJNI.stream_outlet_push_sample__SWIG_38(swigCPtr, this, SWIGTYPE_p_short.getCPtr(data));
  }

  public void push_sample(String data, double timestamp, boolean pushthrough) {
    lslAndroidJNI.stream_outlet_push_sample__SWIG_39(swigCPtr, this, data, timestamp, pushthrough);
  }

  public void push_sample(String data, double timestamp) {
    lslAndroidJNI.stream_outlet_push_sample__SWIG_40(swigCPtr, this, data, timestamp);
  }

  public void push_sample(String data) {
    lslAndroidJNI.stream_outlet_push_sample__SWIG_41(swigCPtr, this, data);
  }

  public void push_sample(SWIGTYPE_p_std__string data, double timestamp, boolean pushthrough) {
    lslAndroidJNI.stream_outlet_push_sample__SWIG_42(swigCPtr, this, SWIGTYPE_p_std__string.getCPtr(data), timestamp, pushthrough);
  }

  public void push_sample(SWIGTYPE_p_std__string data, double timestamp) {
    lslAndroidJNI.stream_outlet_push_sample__SWIG_43(swigCPtr, this, SWIGTYPE_p_std__string.getCPtr(data), timestamp);
  }

  public void push_sample(SWIGTYPE_p_std__string data) {
    lslAndroidJNI.stream_outlet_push_sample__SWIG_44(swigCPtr, this, SWIGTYPE_p_std__string.getCPtr(data));
  }

  public void push_numeric_raw(SWIGTYPE_p_void sample, double timestamp, boolean pushthrough) {
    lslAndroidJNI.stream_outlet_push_numeric_raw__SWIG_0(swigCPtr, this, SWIGTYPE_p_void.getCPtr(sample), timestamp, pushthrough);
  }

  public void push_numeric_raw(SWIGTYPE_p_void sample, double timestamp) {
    lslAndroidJNI.stream_outlet_push_numeric_raw__SWIG_1(swigCPtr, this, SWIGTYPE_p_void.getCPtr(sample), timestamp);
  }

  public void push_numeric_raw(SWIGTYPE_p_void sample) {
    lslAndroidJNI.stream_outlet_push_numeric_raw__SWIG_2(swigCPtr, this, SWIGTYPE_p_void.getCPtr(sample));
  }

  public boolean have_consumers() {
    return lslAndroidJNI.stream_outlet_have_consumers(swigCPtr, this);
  }

  public boolean wait_for_consumers(double timeout) {
    return lslAndroidJNI.stream_outlet_wait_for_consumers(swigCPtr, this, timeout);
  }

  public stream_info info() {
    return new stream_info(lslAndroidJNI.stream_outlet_info(swigCPtr, this), true);
  }

}
