/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.example.hellojni;

public class SWIGTYPE_p_stream_info_impl {
  private long swigCPtr;

  protected SWIGTYPE_p_stream_info_impl(long cPtr, boolean futureUse) {
    swigCPtr = cPtr;
  }

  protected SWIGTYPE_p_stream_info_impl() {
    swigCPtr = 0;
  }

  protected static long getCPtr(SWIGTYPE_p_stream_info_impl obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }
}

