/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class vectorf {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected vectorf(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(vectorf obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        liblslJNI.delete_vectorf(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public vectorf() {
    this(liblslJNI.new_vectorf__SWIG_0(), true);
  }

  public vectorf(long n) {
    this(liblslJNI.new_vectorf__SWIG_1(n), true);
  }

  public long size() {
    return liblslJNI.vectorf_size(swigCPtr, this);
  }

  public long capacity() {
    return liblslJNI.vectorf_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    liblslJNI.vectorf_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return liblslJNI.vectorf_isEmpty(swigCPtr, this);
  }

  public void clear() {
    liblslJNI.vectorf_clear(swigCPtr, this);
  }

  public void add(float x) {
    liblslJNI.vectorf_add(swigCPtr, this, x);
  }

  public float get(int i) {
    return liblslJNI.vectorf_get(swigCPtr, this, i);
  }

  public void set(int i, float val) {
    liblslJNI.vectorf_set(swigCPtr, this, i, val);
  }

}
