/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class vectori {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected vectori(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(vectori obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        liblslJNI.delete_vectori(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public vectori() {
    this(liblslJNI.new_vectori__SWIG_0(), true);
  }

  public vectori(long n) {
    this(liblslJNI.new_vectori__SWIG_1(n), true);
  }

  public long size() {
    return liblslJNI.vectori_size(swigCPtr, this);
  }

  public long capacity() {
    return liblslJNI.vectori_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    liblslJNI.vectori_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return liblslJNI.vectori_isEmpty(swigCPtr, this);
  }

  public void clear() {
    liblslJNI.vectori_clear(swigCPtr, this);
  }

  public void add(int x) {
    liblslJNI.vectori_add(swigCPtr, this, x);
  }

  public int get(int i) {
    return liblslJNI.vectori_get(swigCPtr, this, i);
  }

  public void set(int i, int val) {
    liblslJNI.vectori_set(swigCPtr, this, i, val);
  }

}
