<?php

/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.3
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

// Try to load our extension if it's not already loaded.
if (!extension_loaded('liblsl')) {
  if (strtolower(substr(PHP_OS, 0, 3)) === 'win') {
    if (!dl('php_liblsl.dll')) return;
  } else {
    // PHP_SHLIB_SUFFIX gives 'dylib' on MacOS X but modules are 'so'.
    if (PHP_SHLIB_SUFFIX === 'dylib') {
      if (!dl('liblsl.so')) return;
    } else {
      if (!dl('liblsl.'.PHP_SHLIB_SUFFIX)) return;
    }
  }
}



abstract class liblsl {
	const LSL_IRREGULAR_RATE = LSL_IRREGULAR_RATE;

	const LSL_DEDUCED_TIMESTAMP = LSL_DEDUCED_TIMESTAMP;

	const LSL_FOREVER = LSL_FOREVER;

	const LSL_NO_PREFERENCE = LSL_NO_PREFERENCE;

	const cft_float32 = 1;

	const cft_double64 = 2;

	const cft_string = 3;

	const cft_int32 = 4;

	const cft_int16 = 5;

	const cft_int8 = 6;

	const cft_int64 = 7;

	const cft_undefined = 0;

	const lsl_no_error = 0;

	const lsl_timeout_error = -1;

	const lsl_lost_error = -2;

	const lsl_argument_error = -3;

	const lsl_internal_error = -4;

	static function lsl_protocol_version() {
		return lsl_protocol_version();
	}

	static function lsl_library_version() {
		return lsl_library_version();
	}

	static function lsl_local_clock() {
		return lsl_local_clock();
	}

	static function lsl_resolve_all($buffer,$buffer_elements,$wait_time) {
		return lsl_resolve_all($buffer,$buffer_elements,$wait_time);
	}

	static function lsl_resolve_byprop($buffer,$buffer_elements,$prop,$value,$minimum,$timeout) {
		return lsl_resolve_byprop($buffer,$buffer_elements,$prop,$value,$minimum,$timeout);
	}

	static function lsl_resolve_bypred($buffer,$buffer_elements,$pred,$minimum,$timeout) {
		return lsl_resolve_bypred($buffer,$buffer_elements,$pred,$minimum,$timeout);
	}

	static function lsl_destroy_string($s) {
		lsl_destroy_string($s);
	}

	static function lsl_create_streaminfo($name,$type,$channel_count,$nominal_srate,$channel_format,$source_id) {
		return lsl_create_streaminfo($name,$type,$channel_count,$nominal_srate,$channel_format,$source_id);
	}

	static function lsl_destroy_streaminfo($info) {
		lsl_destroy_streaminfo($info);
	}

	static function lsl_copy_streaminfo($info) {
		return lsl_copy_streaminfo($info);
	}

	static function lsl_get_name($info) {
		return lsl_get_name($info);
	}

	static function lsl_get_type($info) {
		return lsl_get_type($info);
	}

	static function lsl_get_channel_count($info) {
		return lsl_get_channel_count($info);
	}

	static function lsl_get_nominal_srate($info) {
		return lsl_get_nominal_srate($info);
	}

	static function lsl_get_channel_format($info) {
		return lsl_get_channel_format($info);
	}

	static function lsl_get_source_id($info) {
		return lsl_get_source_id($info);
	}

	static function lsl_get_version($info) {
		return lsl_get_version($info);
	}

	static function lsl_get_created_at($info) {
		return lsl_get_created_at($info);
	}

	static function lsl_get_uid($info) {
		return lsl_get_uid($info);
	}

	static function lsl_get_session_id($info) {
		return lsl_get_session_id($info);
	}

	static function lsl_get_hostname($info) {
		return lsl_get_hostname($info);
	}

	static function lsl_get_desc($info) {
		return lsl_get_desc($info);
	}

	static function lsl_get_xml($info) {
		return lsl_get_xml($info);
	}

	static function lsl_get_channel_bytes($info) {
		return lsl_get_channel_bytes($info);
	}

	static function lsl_get_sample_bytes($info) {
		return lsl_get_sample_bytes($info);
	}

	static function lsl_streaminfo_from_xml($xml) {
		return lsl_streaminfo_from_xml($xml);
	}

	static function lsl_create_outlet($info,$chunk_size,$max_buffered) {
		return lsl_create_outlet($info,$chunk_size,$max_buffered);
	}

	static function lsl_destroy_outlet($out) {
		lsl_destroy_outlet($out);
	}

	static function lsl_push_sample_f($out,$data) {
		return lsl_push_sample_f($out,$data);
	}

	static function lsl_push_sample_ft($out,$data,$timestamp) {
		return lsl_push_sample_ft($out,$data,$timestamp);
	}

	static function lsl_push_sample_ftp($out,$data,$timestamp,$pushthrough) {
		return lsl_push_sample_ftp($out,$data,$timestamp,$pushthrough);
	}

	static function lsl_push_sample_d($out,$data) {
		return lsl_push_sample_d($out,$data);
	}

	static function lsl_push_sample_dt($out,$data,$timestamp) {
		return lsl_push_sample_dt($out,$data,$timestamp);
	}

	static function lsl_push_sample_dtp($out,$data,$timestamp,$pushthrough) {
		return lsl_push_sample_dtp($out,$data,$timestamp,$pushthrough);
	}

	static function lsl_push_sample_l($out,$data) {
		return lsl_push_sample_l($out,$data);
	}

	static function lsl_push_sample_lt($out,$data,$timestamp) {
		return lsl_push_sample_lt($out,$data,$timestamp);
	}

	static function lsl_push_sample_ltp($out,$data,$timestamp,$pushthrough) {
		return lsl_push_sample_ltp($out,$data,$timestamp,$pushthrough);
	}

	static function lsl_push_sample_i($out,$data) {
		return lsl_push_sample_i($out,$data);
	}

	static function lsl_push_sample_it($out,$data,$timestamp) {
		return lsl_push_sample_it($out,$data,$timestamp);
	}

	static function lsl_push_sample_itp($out,$data,$timestamp,$pushthrough) {
		return lsl_push_sample_itp($out,$data,$timestamp,$pushthrough);
	}

	static function lsl_push_sample_s($out,$data) {
		return lsl_push_sample_s($out,$data);
	}

	static function lsl_push_sample_st($out,$data,$timestamp) {
		return lsl_push_sample_st($out,$data,$timestamp);
	}

	static function lsl_push_sample_stp($out,$data,$timestamp,$pushthrough) {
		return lsl_push_sample_stp($out,$data,$timestamp,$pushthrough);
	}

	static function lsl_push_sample_c($out,$data) {
		return lsl_push_sample_c($out,$data);
	}

	static function lsl_push_sample_ct($out,$data,$timestamp) {
		return lsl_push_sample_ct($out,$data,$timestamp);
	}

	static function lsl_push_sample_ctp($out,$data,$timestamp,$pushthrough) {
		return lsl_push_sample_ctp($out,$data,$timestamp,$pushthrough);
	}

	static function lsl_push_sample_str($out,$data) {
		return lsl_push_sample_str($out,$data);
	}

	static function lsl_push_sample_strt($out,$data,$timestamp) {
		return lsl_push_sample_strt($out,$data,$timestamp);
	}

	static function lsl_push_sample_strtp($out,$data,$timestamp,$pushthrough) {
		return lsl_push_sample_strtp($out,$data,$timestamp,$pushthrough);
	}

	static function lsl_push_sample_buf($out,$data,$lengths) {
		return lsl_push_sample_buf($out,$data,$lengths);
	}

	static function lsl_push_sample_buft($out,$data,$lengths,$timestamp) {
		return lsl_push_sample_buft($out,$data,$lengths,$timestamp);
	}

	static function lsl_push_sample_buftp($out,$data,$lengths,$timestamp,$pushthrough) {
		return lsl_push_sample_buftp($out,$data,$lengths,$timestamp,$pushthrough);
	}

	static function lsl_push_sample_v($out,$data) {
		return lsl_push_sample_v($out,$data);
	}

	static function lsl_push_sample_vt($out,$data,$timestamp) {
		return lsl_push_sample_vt($out,$data,$timestamp);
	}

	static function lsl_push_sample_vtp($out,$data,$timestamp,$pushthrough) {
		return lsl_push_sample_vtp($out,$data,$timestamp,$pushthrough);
	}

	static function lsl_push_chunk_f($out,$data,$data_elements) {
		return lsl_push_chunk_f($out,$data,$data_elements);
	}

	static function lsl_push_chunk_ft($out,$data,$data_elements,$timestamp) {
		return lsl_push_chunk_ft($out,$data,$data_elements,$timestamp);
	}

	static function lsl_push_chunk_ftp($out,$data,$data_elements,$timestamp,$pushthrough) {
		return lsl_push_chunk_ftp($out,$data,$data_elements,$timestamp,$pushthrough);
	}

	static function lsl_push_chunk_ftn($out,$data,$data_elements,$timestamps) {
		return lsl_push_chunk_ftn($out,$data,$data_elements,$timestamps);
	}

	static function lsl_push_chunk_ftnp($out,$data,$data_elements,$timestamps,$pushthrough) {
		return lsl_push_chunk_ftnp($out,$data,$data_elements,$timestamps,$pushthrough);
	}

	static function lsl_push_chunk_d($out,$data,$data_elements) {
		return lsl_push_chunk_d($out,$data,$data_elements);
	}

	static function lsl_push_chunk_dt($out,$data,$data_elements,$timestamp) {
		return lsl_push_chunk_dt($out,$data,$data_elements,$timestamp);
	}

	static function lsl_push_chunk_dtp($out,$data,$data_elements,$timestamp,$pushthrough) {
		return lsl_push_chunk_dtp($out,$data,$data_elements,$timestamp,$pushthrough);
	}

	static function lsl_push_chunk_dtn($out,$data,$data_elements,$timestamps) {
		return lsl_push_chunk_dtn($out,$data,$data_elements,$timestamps);
	}

	static function lsl_push_chunk_dtnp($out,$data,$data_elements,$timestamps,$pushthrough) {
		return lsl_push_chunk_dtnp($out,$data,$data_elements,$timestamps,$pushthrough);
	}

	static function lsl_push_chunk_l($out,$data,$data_elements) {
		return lsl_push_chunk_l($out,$data,$data_elements);
	}

	static function lsl_push_chunk_lt($out,$data,$data_elements,$timestamp) {
		return lsl_push_chunk_lt($out,$data,$data_elements,$timestamp);
	}

	static function lsl_push_chunk_ltp($out,$data,$data_elements,$timestamp,$pushthrough) {
		return lsl_push_chunk_ltp($out,$data,$data_elements,$timestamp,$pushthrough);
	}

	static function lsl_push_chunk_ltn($out,$data,$data_elements,$timestamps) {
		return lsl_push_chunk_ltn($out,$data,$data_elements,$timestamps);
	}

	static function lsl_push_chunk_ltnp($out,$data,$data_elements,$timestamps,$pushthrough) {
		return lsl_push_chunk_ltnp($out,$data,$data_elements,$timestamps,$pushthrough);
	}

	static function lsl_push_chunk_i($out,$data,$data_elements) {
		return lsl_push_chunk_i($out,$data,$data_elements);
	}

	static function lsl_push_chunk_it($out,$data,$data_elements,$timestamp) {
		return lsl_push_chunk_it($out,$data,$data_elements,$timestamp);
	}

	static function lsl_push_chunk_itp($out,$data,$data_elements,$timestamp,$pushthrough) {
		return lsl_push_chunk_itp($out,$data,$data_elements,$timestamp,$pushthrough);
	}

	static function lsl_push_chunk_itn($out,$data,$data_elements,$timestamps) {
		return lsl_push_chunk_itn($out,$data,$data_elements,$timestamps);
	}

	static function lsl_push_chunk_itnp($out,$data,$data_elements,$timestamps,$pushthrough) {
		return lsl_push_chunk_itnp($out,$data,$data_elements,$timestamps,$pushthrough);
	}

	static function lsl_push_chunk_s($out,$data,$data_elements) {
		return lsl_push_chunk_s($out,$data,$data_elements);
	}

	static function lsl_push_chunk_st($out,$data,$data_elements,$timestamp) {
		return lsl_push_chunk_st($out,$data,$data_elements,$timestamp);
	}

	static function lsl_push_chunk_stp($out,$data,$data_elements,$timestamp,$pushthrough) {
		return lsl_push_chunk_stp($out,$data,$data_elements,$timestamp,$pushthrough);
	}

	static function lsl_push_chunk_stn($out,$data,$data_elements,$timestamps) {
		return lsl_push_chunk_stn($out,$data,$data_elements,$timestamps);
	}

	static function lsl_push_chunk_stnp($out,$data,$data_elements,$timestamps,$pushthrough) {
		return lsl_push_chunk_stnp($out,$data,$data_elements,$timestamps,$pushthrough);
	}

	static function lsl_push_chunk_c($out,$data,$data_elements) {
		return lsl_push_chunk_c($out,$data,$data_elements);
	}

	static function lsl_push_chunk_ct($out,$data,$data_elements,$timestamp) {
		return lsl_push_chunk_ct($out,$data,$data_elements,$timestamp);
	}

	static function lsl_push_chunk_ctp($out,$data,$data_elements,$timestamp,$pushthrough) {
		return lsl_push_chunk_ctp($out,$data,$data_elements,$timestamp,$pushthrough);
	}

	static function lsl_push_chunk_ctn($out,$data,$data_elements,$timestamps) {
		return lsl_push_chunk_ctn($out,$data,$data_elements,$timestamps);
	}

	static function lsl_push_chunk_ctnp($out,$data,$data_elements,$timestamps,$pushthrough) {
		return lsl_push_chunk_ctnp($out,$data,$data_elements,$timestamps,$pushthrough);
	}

	static function lsl_push_chunk_str($out,$data,$data_elements) {
		return lsl_push_chunk_str($out,$data,$data_elements);
	}

	static function lsl_push_chunk_strt($out,$data,$data_elements,$timestamp) {
		return lsl_push_chunk_strt($out,$data,$data_elements,$timestamp);
	}

	static function lsl_push_chunk_strtp($out,$data,$data_elements,$timestamp,$pushthrough) {
		return lsl_push_chunk_strtp($out,$data,$data_elements,$timestamp,$pushthrough);
	}

	static function lsl_push_chunk_strtn($out,$data,$data_elements,$timestamps) {
		return lsl_push_chunk_strtn($out,$data,$data_elements,$timestamps);
	}

	static function lsl_push_chunk_strtnp($out,$data,$data_elements,$timestamps,$pushthrough) {
		return lsl_push_chunk_strtnp($out,$data,$data_elements,$timestamps,$pushthrough);
	}

	static function lsl_push_chunk_buf($out,$data,$lengths,$data_elements) {
		return lsl_push_chunk_buf($out,$data,$lengths,$data_elements);
	}

	static function lsl_push_chunk_buft($out,$data,$lengths,$data_elements,$timestamp) {
		return lsl_push_chunk_buft($out,$data,$lengths,$data_elements,$timestamp);
	}

	static function lsl_push_chunk_buftp($out,$data,$lengths,$data_elements,$timestamp,$pushthrough) {
		return lsl_push_chunk_buftp($out,$data,$lengths,$data_elements,$timestamp,$pushthrough);
	}

	static function lsl_push_chunk_buftn($out,$data,$lengths,$data_elements,$timestamps) {
		return lsl_push_chunk_buftn($out,$data,$lengths,$data_elements,$timestamps);
	}

	static function lsl_push_chunk_buftnp($out,$data,$lengths,$data_elements,$timestamps,$pushthrough) {
		return lsl_push_chunk_buftnp($out,$data,$lengths,$data_elements,$timestamps,$pushthrough);
	}

	static function lsl_have_consumers($out) {
		return lsl_have_consumers($out);
	}

	static function lsl_wait_for_consumers($out,$timeout) {
		return lsl_wait_for_consumers($out,$timeout);
	}

	static function lsl_get_info($out) {
		return lsl_get_info($out);
	}

	static function lsl_create_inlet($info,$max_buflen,$max_chunklen,$recover) {
		return lsl_create_inlet($info,$max_buflen,$max_chunklen,$recover);
	}

	static function lsl_destroy_inlet($in) {
		lsl_destroy_inlet($in);
	}

	static function lsl_get_fullinfo($in,$timeout,$ec) {
		return lsl_get_fullinfo($in,$timeout,$ec);
	}

	static function lsl_open_stream($in,$timeout,$ec) {
		lsl_open_stream($in,$timeout,$ec);
	}

	static function lsl_close_stream($in) {
		lsl_close_stream($in);
	}

	static function lsl_time_correction($in,$timeout,$ec) {
		return lsl_time_correction($in,$timeout,$ec);
	}

	static function lsl_pull_sample_f($in,$buffer,$buffer_elements,$timeout,$ec) {
		return lsl_pull_sample_f($in,$buffer,$buffer_elements,$timeout,$ec);
	}

	static function lsl_pull_sample_d($in,$buffer,$buffer_elements,$timeout,$ec) {
		return lsl_pull_sample_d($in,$buffer,$buffer_elements,$timeout,$ec);
	}

	static function lsl_pull_sample_l($in,$buffer,$buffer_elements,$timeout,$ec) {
		return lsl_pull_sample_l($in,$buffer,$buffer_elements,$timeout,$ec);
	}

	static function lsl_pull_sample_i($in,$buffer,$buffer_elements,$timeout,$ec) {
		return lsl_pull_sample_i($in,$buffer,$buffer_elements,$timeout,$ec);
	}

	static function lsl_pull_sample_s($in,$buffer,$buffer_elements,$timeout,$ec) {
		return lsl_pull_sample_s($in,$buffer,$buffer_elements,$timeout,$ec);
	}

	static function lsl_pull_sample_c($in,$buffer,$buffer_elements,$timeout,$ec) {
		return lsl_pull_sample_c($in,$buffer,$buffer_elements,$timeout,$ec);
	}

	static function lsl_pull_sample_str($in,$buffer,$buffer_elements,$timeout,$ec) {
		return lsl_pull_sample_str($in,$buffer,$buffer_elements,$timeout,$ec);
	}

	static function lsl_pull_sample_buf($in,$buffer,$buffer_lengths,$buffer_elements,$timeout,$ec) {
		return lsl_pull_sample_buf($in,$buffer,$buffer_lengths,$buffer_elements,$timeout,$ec);
	}

	static function lsl_pull_sample_v($in,$buffer,$buffer_bytes,$timeout,$ec) {
		return lsl_pull_sample_v($in,$buffer,$buffer_bytes,$timeout,$ec);
	}

	static function lsl_pull_chunk_f($in,$data_buffer,$timestamp_buffer,$data_buffer_elements,$timestamp_buffer_elements,$timeout,$ec) {
		return lsl_pull_chunk_f($in,$data_buffer,$timestamp_buffer,$data_buffer_elements,$timestamp_buffer_elements,$timeout,$ec);
	}

	static function lsl_pull_chunk_d($in,$data_buffer,$timestamp_buffer,$data_buffer_elements,$timestamp_buffer_elements,$timeout,$ec) {
		return lsl_pull_chunk_d($in,$data_buffer,$timestamp_buffer,$data_buffer_elements,$timestamp_buffer_elements,$timeout,$ec);
	}

	static function lsl_pull_chunk_l($in,$data_buffer,$timestamp_buffer,$data_buffer_elements,$timestamp_buffer_elements,$timeout,$ec) {
		return lsl_pull_chunk_l($in,$data_buffer,$timestamp_buffer,$data_buffer_elements,$timestamp_buffer_elements,$timeout,$ec);
	}

	static function lsl_pull_chunk_i($in,$data_buffer,$timestamp_buffer,$data_buffer_elements,$timestamp_buffer_elements,$timeout,$ec) {
		return lsl_pull_chunk_i($in,$data_buffer,$timestamp_buffer,$data_buffer_elements,$timestamp_buffer_elements,$timeout,$ec);
	}

	static function lsl_pull_chunk_s($in,$data_buffer,$timestamp_buffer,$data_buffer_elements,$timestamp_buffer_elements,$timeout,$ec) {
		return lsl_pull_chunk_s($in,$data_buffer,$timestamp_buffer,$data_buffer_elements,$timestamp_buffer_elements,$timeout,$ec);
	}

	static function lsl_pull_chunk_c($in,$data_buffer,$timestamp_buffer,$data_buffer_elements,$timestamp_buffer_elements,$timeout,$ec) {
		return lsl_pull_chunk_c($in,$data_buffer,$timestamp_buffer,$data_buffer_elements,$timestamp_buffer_elements,$timeout,$ec);
	}

	static function lsl_pull_chunk_str($in,$data_buffer,$timestamp_buffer,$data_buffer_elements,$timestamp_buffer_elements,$timeout,$ec) {
		return lsl_pull_chunk_str($in,$data_buffer,$timestamp_buffer,$data_buffer_elements,$timestamp_buffer_elements,$timeout,$ec);
	}

	static function lsl_pull_chunk_buf($in,$data_buffer,$lengths_buffer,$timestamp_buffer,$data_buffer_elements,$timestamp_buffer_elements,$timeout,$ec) {
		return lsl_pull_chunk_buf($in,$data_buffer,$lengths_buffer,$timestamp_buffer,$data_buffer_elements,$timestamp_buffer_elements,$timeout,$ec);
	}

	static function lsl_samples_available($in) {
		return lsl_samples_available($in);
	}

	static function lsl_was_clock_reset($in) {
		return lsl_was_clock_reset($in);
	}

	static function lsl_first_child($e) {
		return lsl_first_child($e);
	}

	static function lsl_last_child($e) {
		return lsl_last_child($e);
	}

	static function lsl_next_sibling($e) {
		return lsl_next_sibling($e);
	}

	static function lsl_previous_sibling($e) {
		return lsl_previous_sibling($e);
	}

	static function lsl_parent($e) {
		return lsl_parent($e);
	}

	static function lsl_child($e,$name) {
		return lsl_child($e,$name);
	}

	static function lsl_next_sibling_n($e,$name) {
		return lsl_next_sibling_n($e,$name);
	}

	static function lsl_previous_sibling_n($e,$name) {
		return lsl_previous_sibling_n($e,$name);
	}

	static function lsl_empty($e) {
		return lsl_empty($e);
	}

	static function lsl_is_text($e) {
		return lsl_is_text($e);
	}

	static function lsl_name($e) {
		return lsl_name($e);
	}

	static function lsl_value($e) {
		return lsl_value($e);
	}

	static function lsl_child_value($e) {
		return lsl_child_value($e);
	}

	static function lsl_child_value_n($e,$name) {
		return lsl_child_value_n($e,$name);
	}

	static function lsl_append_child_value($e,$name,$value) {
		return lsl_append_child_value($e,$name,$value);
	}

	static function lsl_prepend_child_value($e,$name,$value) {
		return lsl_prepend_child_value($e,$name,$value);
	}

	static function lsl_set_child_value($e,$name,$value) {
		return lsl_set_child_value($e,$name,$value);
	}

	static function lsl_set_name($e,$rhs) {
		return lsl_set_name($e,$rhs);
	}

	static function lsl_set_value($e,$rhs) {
		return lsl_set_value($e,$rhs);
	}

	static function lsl_append_child($e,$name) {
		return lsl_append_child($e,$name);
	}

	static function lsl_prepend_child($e,$name) {
		return lsl_prepend_child($e,$name);
	}

	static function lsl_append_copy($e,$e2) {
		return lsl_append_copy($e,$e2);
	}

	static function lsl_prepend_copy($e,$e2) {
		return lsl_prepend_copy($e,$e2);
	}

	static function lsl_remove_child_n($e,$name) {
		lsl_remove_child_n($e,$name);
	}

	static function lsl_remove_child($e,$e2) {
		lsl_remove_child($e,$e2);
	}

	static function lsl_create_continuous_resolver($forget_after) {
		return lsl_create_continuous_resolver($forget_after);
	}

	static function lsl_create_continuous_resolver_byprop($prop,$value,$forget_after) {
		return lsl_create_continuous_resolver_byprop($prop,$value,$forget_after);
	}

	static function lsl_create_continuous_resolver_bypred($pred,$forget_after) {
		return lsl_create_continuous_resolver_bypred($pred,$forget_after);
	}

	static function lsl_resolver_results($res,$buffer,$buffer_elements) {
		return lsl_resolver_results($res,$buffer,$buffer_elements);
	}

	static function lsl_destroy_continuous_resolver($res) {
		lsl_destroy_continuous_resolver($res);
	}
}

/* PHP Proxy Classes */

?>
