/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.ucsd.sccn.lsl;

public class SWIGTYPE_p_lsl_streaminfo {
  private long swigCPtr;

  protected SWIGTYPE_p_lsl_streaminfo(long cPtr, boolean futureUse) {
    swigCPtr = cPtr;
  }

  protected SWIGTYPE_p_lsl_streaminfo() {
    swigCPtr = 0;
  }

  protected static long getCPtr(SWIGTYPE_p_lsl_streaminfo obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }
}

