/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.3
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

#ifndef PHP_LIBLSL_H
#define PHP_LIBLSL_H

extern zend_module_entry liblsl_module_entry;
#define phpext_liblsl_ptr &liblsl_module_entry

#ifdef PHP_WIN32
# define PHP_LIBLSL_API __declspec(dllexport)
#else
# define PHP_LIBLSL_API
#endif

#ifdef ZTS
#include "TSRM.h"
#endif

PHP_MINIT_FUNCTION(liblsl);
PHP_MSHUTDOWN_FUNCTION(liblsl);
PHP_RINIT_FUNCTION(liblsl);
PHP_RSHUTDOWN_FUNCTION(liblsl);
PHP_MINFO_FUNCTION(liblsl);

ZEND_NAMED_FUNCTION(_wrap_lsl_protocol_version);
ZEND_NAMED_FUNCTION(_wrap_lsl_library_version);
ZEND_NAMED_FUNCTION(_wrap_lsl_local_clock);
ZEND_NAMED_FUNCTION(_wrap_lsl_resolve_all);
ZEND_NAMED_FUNCTION(_wrap_lsl_resolve_byprop);
ZEND_NAMED_FUNCTION(_wrap_lsl_resolve_bypred);
ZEND_NAMED_FUNCTION(_wrap_lsl_destroy_string);
ZEND_NAMED_FUNCTION(_wrap_lsl_create_streaminfo);
ZEND_NAMED_FUNCTION(_wrap_lsl_destroy_streaminfo);
ZEND_NAMED_FUNCTION(_wrap_lsl_copy_streaminfo);
ZEND_NAMED_FUNCTION(_wrap_lsl_get_name);
ZEND_NAMED_FUNCTION(_wrap_lsl_get_type);
ZEND_NAMED_FUNCTION(_wrap_lsl_get_channel_count);
ZEND_NAMED_FUNCTION(_wrap_lsl_get_nominal_srate);
ZEND_NAMED_FUNCTION(_wrap_lsl_get_channel_format);
ZEND_NAMED_FUNCTION(_wrap_lsl_get_source_id);
ZEND_NAMED_FUNCTION(_wrap_lsl_get_version);
ZEND_NAMED_FUNCTION(_wrap_lsl_get_created_at);
ZEND_NAMED_FUNCTION(_wrap_lsl_get_uid);
ZEND_NAMED_FUNCTION(_wrap_lsl_get_session_id);
ZEND_NAMED_FUNCTION(_wrap_lsl_get_hostname);
ZEND_NAMED_FUNCTION(_wrap_lsl_get_desc);
ZEND_NAMED_FUNCTION(_wrap_lsl_get_xml);
ZEND_NAMED_FUNCTION(_wrap_lsl_get_channel_bytes);
ZEND_NAMED_FUNCTION(_wrap_lsl_get_sample_bytes);
ZEND_NAMED_FUNCTION(_wrap_lsl_streaminfo_from_xml);
ZEND_NAMED_FUNCTION(_wrap_lsl_create_outlet);
ZEND_NAMED_FUNCTION(_wrap_lsl_destroy_outlet);
ZEND_NAMED_FUNCTION(_wrap_lsl_push_sample_f);
ZEND_NAMED_FUNCTION(_wrap_lsl_push_sample_ft);
ZEND_NAMED_FUNCTION(_wrap_lsl_push_sample_ftp);
ZEND_NAMED_FUNCTION(_wrap_lsl_push_sample_d);
ZEND_NAMED_FUNCTION(_wrap_lsl_push_sample_dt);
ZEND_NAMED_FUNCTION(_wrap_lsl_push_sample_dtp);
ZEND_NAMED_FUNCTION(_wrap_lsl_push_sample_l);
ZEND_NAMED_FUNCTION(_wrap_lsl_push_sample_lt);
ZEND_NAMED_FUNCTION(_wrap_lsl_push_sample_ltp);
ZEND_NAMED_FUNCTION(_wrap_lsl_push_sample_i);
ZEND_NAMED_FUNCTION(_wrap_lsl_push_sample_it);
ZEND_NAMED_FUNCTION(_wrap_lsl_push_sample_itp);
ZEND_NAMED_FUNCTION(_wrap_lsl_push_sample_s);
ZEND_NAMED_FUNCTION(_wrap_lsl_push_sample_st);
ZEND_NAMED_FUNCTION(_wrap_lsl_push_sample_stp);
ZEND_NAMED_FUNCTION(_wrap_lsl_push_sample_c);
ZEND_NAMED_FUNCTION(_wrap_lsl_push_sample_ct);
ZEND_NAMED_FUNCTION(_wrap_lsl_push_sample_ctp);
ZEND_NAMED_FUNCTION(_wrap_lsl_push_sample_str);
ZEND_NAMED_FUNCTION(_wrap_lsl_push_sample_strt);
ZEND_NAMED_FUNCTION(_wrap_lsl_push_sample_strtp);
ZEND_NAMED_FUNCTION(_wrap_lsl_push_sample_buf);
ZEND_NAMED_FUNCTION(_wrap_lsl_push_sample_buft);
ZEND_NAMED_FUNCTION(_wrap_lsl_push_sample_buftp);
ZEND_NAMED_FUNCTION(_wrap_lsl_push_sample_v);
ZEND_NAMED_FUNCTION(_wrap_lsl_push_sample_vt);
ZEND_NAMED_FUNCTION(_wrap_lsl_push_sample_vtp);
ZEND_NAMED_FUNCTION(_wrap_lsl_push_chunk_f);
ZEND_NAMED_FUNCTION(_wrap_lsl_push_chunk_ft);
ZEND_NAMED_FUNCTION(_wrap_lsl_push_chunk_ftp);
ZEND_NAMED_FUNCTION(_wrap_lsl_push_chunk_ftn);
ZEND_NAMED_FUNCTION(_wrap_lsl_push_chunk_ftnp);
ZEND_NAMED_FUNCTION(_wrap_lsl_push_chunk_d);
ZEND_NAMED_FUNCTION(_wrap_lsl_push_chunk_dt);
ZEND_NAMED_FUNCTION(_wrap_lsl_push_chunk_dtp);
ZEND_NAMED_FUNCTION(_wrap_lsl_push_chunk_dtn);
ZEND_NAMED_FUNCTION(_wrap_lsl_push_chunk_dtnp);
ZEND_NAMED_FUNCTION(_wrap_lsl_push_chunk_l);
ZEND_NAMED_FUNCTION(_wrap_lsl_push_chunk_lt);
ZEND_NAMED_FUNCTION(_wrap_lsl_push_chunk_ltp);
ZEND_NAMED_FUNCTION(_wrap_lsl_push_chunk_ltn);
ZEND_NAMED_FUNCTION(_wrap_lsl_push_chunk_ltnp);
ZEND_NAMED_FUNCTION(_wrap_lsl_push_chunk_i);
ZEND_NAMED_FUNCTION(_wrap_lsl_push_chunk_it);
ZEND_NAMED_FUNCTION(_wrap_lsl_push_chunk_itp);
ZEND_NAMED_FUNCTION(_wrap_lsl_push_chunk_itn);
ZEND_NAMED_FUNCTION(_wrap_lsl_push_chunk_itnp);
ZEND_NAMED_FUNCTION(_wrap_lsl_push_chunk_s);
ZEND_NAMED_FUNCTION(_wrap_lsl_push_chunk_st);
ZEND_NAMED_FUNCTION(_wrap_lsl_push_chunk_stp);
ZEND_NAMED_FUNCTION(_wrap_lsl_push_chunk_stn);
ZEND_NAMED_FUNCTION(_wrap_lsl_push_chunk_stnp);
ZEND_NAMED_FUNCTION(_wrap_lsl_push_chunk_c);
ZEND_NAMED_FUNCTION(_wrap_lsl_push_chunk_ct);
ZEND_NAMED_FUNCTION(_wrap_lsl_push_chunk_ctp);
ZEND_NAMED_FUNCTION(_wrap_lsl_push_chunk_ctn);
ZEND_NAMED_FUNCTION(_wrap_lsl_push_chunk_ctnp);
ZEND_NAMED_FUNCTION(_wrap_lsl_push_chunk_str);
ZEND_NAMED_FUNCTION(_wrap_lsl_push_chunk_strt);
ZEND_NAMED_FUNCTION(_wrap_lsl_push_chunk_strtp);
ZEND_NAMED_FUNCTION(_wrap_lsl_push_chunk_strtn);
ZEND_NAMED_FUNCTION(_wrap_lsl_push_chunk_strtnp);
ZEND_NAMED_FUNCTION(_wrap_lsl_push_chunk_buf);
ZEND_NAMED_FUNCTION(_wrap_lsl_push_chunk_buft);
ZEND_NAMED_FUNCTION(_wrap_lsl_push_chunk_buftp);
ZEND_NAMED_FUNCTION(_wrap_lsl_push_chunk_buftn);
ZEND_NAMED_FUNCTION(_wrap_lsl_push_chunk_buftnp);
ZEND_NAMED_FUNCTION(_wrap_lsl_have_consumers);
ZEND_NAMED_FUNCTION(_wrap_lsl_wait_for_consumers);
ZEND_NAMED_FUNCTION(_wrap_lsl_get_info);
ZEND_NAMED_FUNCTION(_wrap_lsl_create_inlet);
ZEND_NAMED_FUNCTION(_wrap_lsl_destroy_inlet);
ZEND_NAMED_FUNCTION(_wrap_lsl_get_fullinfo);
ZEND_NAMED_FUNCTION(_wrap_lsl_open_stream);
ZEND_NAMED_FUNCTION(_wrap_lsl_close_stream);
ZEND_NAMED_FUNCTION(_wrap_lsl_time_correction);
ZEND_NAMED_FUNCTION(_wrap_lsl_pull_sample_f);
ZEND_NAMED_FUNCTION(_wrap_lsl_pull_sample_d);
ZEND_NAMED_FUNCTION(_wrap_lsl_pull_sample_l);
ZEND_NAMED_FUNCTION(_wrap_lsl_pull_sample_i);
ZEND_NAMED_FUNCTION(_wrap_lsl_pull_sample_s);
ZEND_NAMED_FUNCTION(_wrap_lsl_pull_sample_c);
ZEND_NAMED_FUNCTION(_wrap_lsl_pull_sample_str);
ZEND_NAMED_FUNCTION(_wrap_lsl_pull_sample_buf);
ZEND_NAMED_FUNCTION(_wrap_lsl_pull_sample_v);
ZEND_NAMED_FUNCTION(_wrap_lsl_pull_chunk_f);
ZEND_NAMED_FUNCTION(_wrap_lsl_pull_chunk_d);
ZEND_NAMED_FUNCTION(_wrap_lsl_pull_chunk_l);
ZEND_NAMED_FUNCTION(_wrap_lsl_pull_chunk_i);
ZEND_NAMED_FUNCTION(_wrap_lsl_pull_chunk_s);
ZEND_NAMED_FUNCTION(_wrap_lsl_pull_chunk_c);
ZEND_NAMED_FUNCTION(_wrap_lsl_pull_chunk_str);
ZEND_NAMED_FUNCTION(_wrap_lsl_pull_chunk_buf);
ZEND_NAMED_FUNCTION(_wrap_lsl_samples_available);
ZEND_NAMED_FUNCTION(_wrap_lsl_was_clock_reset);
ZEND_NAMED_FUNCTION(_wrap_lsl_first_child);
ZEND_NAMED_FUNCTION(_wrap_lsl_last_child);
ZEND_NAMED_FUNCTION(_wrap_lsl_next_sibling);
ZEND_NAMED_FUNCTION(_wrap_lsl_previous_sibling);
ZEND_NAMED_FUNCTION(_wrap_lsl_parent);
ZEND_NAMED_FUNCTION(_wrap_lsl_child);
ZEND_NAMED_FUNCTION(_wrap_lsl_next_sibling_n);
ZEND_NAMED_FUNCTION(_wrap_lsl_previous_sibling_n);
ZEND_NAMED_FUNCTION(_wrap_lsl_empty);
ZEND_NAMED_FUNCTION(_wrap_lsl_is_text);
ZEND_NAMED_FUNCTION(_wrap_lsl_name);
ZEND_NAMED_FUNCTION(_wrap_lsl_value);
ZEND_NAMED_FUNCTION(_wrap_lsl_child_value);
ZEND_NAMED_FUNCTION(_wrap_lsl_child_value_n);
ZEND_NAMED_FUNCTION(_wrap_lsl_append_child_value);
ZEND_NAMED_FUNCTION(_wrap_lsl_prepend_child_value);
ZEND_NAMED_FUNCTION(_wrap_lsl_set_child_value);
ZEND_NAMED_FUNCTION(_wrap_lsl_set_name);
ZEND_NAMED_FUNCTION(_wrap_lsl_set_value);
ZEND_NAMED_FUNCTION(_wrap_lsl_append_child);
ZEND_NAMED_FUNCTION(_wrap_lsl_prepend_child);
ZEND_NAMED_FUNCTION(_wrap_lsl_append_copy);
ZEND_NAMED_FUNCTION(_wrap_lsl_prepend_copy);
ZEND_NAMED_FUNCTION(_wrap_lsl_remove_child_n);
ZEND_NAMED_FUNCTION(_wrap_lsl_remove_child);
ZEND_NAMED_FUNCTION(_wrap_lsl_create_continuous_resolver);
ZEND_NAMED_FUNCTION(_wrap_lsl_create_continuous_resolver_byprop);
ZEND_NAMED_FUNCTION(_wrap_lsl_create_continuous_resolver_bypred);
ZEND_NAMED_FUNCTION(_wrap_lsl_resolver_results);
ZEND_NAMED_FUNCTION(_wrap_lsl_destroy_continuous_resolver);
#endif /* PHP_LIBLSL_H */
